### ISSUE TITLE
Исправить библиотеку serial ()

### ISSUE THREAD

**Issue by pavlov-v** [pavlov-v/daveplus#1]
В текущей версии библиотеки serial используется подтычка в виде mytime с функцией gettimeofday() по причине отсутствия требуемой функции в windows. Переписать в простую функцию.

**Comment by dizi-ai** [comment]
понял, попробую разобраться

**Comment by dizi-ai** [comment]
вопрос, там структура timeval по ссылке передается а что за структура неизвестно, я могу в mytime.h ее объявить, дать ей поля год/месяц/день/час/минута/секунда сойдет?

**Comment by pavlov-v** [comment]
Ну да как удобней будет.
И кстати посмотри как правильно контрибьютить https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project
там на русском есть

**Comment by dizi-ai** [comment]
почитаю , спасибо и еще ты можешь ссылку кинуть, чтобы период слайона заново запустить

**Comment by pavlov-v** [comment]
https://gist.github.com/Pixke/d088db314dfbe87c71be8f9f726c6e0e
